### PR TITLE
Cmake

### LINKED ISSUE #13: cmake packaging
I have started to look at the cmake packaging to make it easier for an external project to link with differnet parts of Nelson. I have some questions regarding which changes you would accept:

1] Install pattern

It is quite common on Linux and MacOS to install binaries directly under PREFIX/bin and PREFIX/lib, and to install public headers under PREFIX/include/PROJECT_NAME. The conda distribution provides a similar files tree on Windows, so that the install is quite similar on all the platforms. In the case of Nelson, adopting such a pattern means:
- the install directory becomes `${CMAKE_INSTALL_PREFIX}` instead of  `${CMAKE_INSTALL_PREFIX}Nelson-${Nelson_VERSION_MAJOR}.${Nelson_VERSION_MINOR}.${Nelson_VERSION_MAINTENANCE}`
- the platform subfolder under `bin` is removed.

Notice that these changes are independent.

2] CMake targets and exports

Exporting and installing the targets used to build the Nelson libraires would simplify a lot the link with them in downstream projects. One would simply write `find_package(Nelson)` followed by `target_link_libraries(myLib PRIVATE Nelson::interpreter)` for instance, and would get the include_directories and dependencies of `Nelson::interpreter` for free.

This requires two kinds of changes:
- The addition of a new `nelsonTargets.cmake` file, that would embed all the targets, as long as `NelsonConfig.cmake` and `NelsonVersionConfig.cmake`.
- rewriting the different `CMakeLists.txt` to use target properties instead of global properties

### PR DESCRIPTION
**Pull request by JohanMabille**
Fixes #13.

Although this should be usable, we can go further:
- Add targets for pure header modules (such as loverload)
- use external fmt instead of vendoring it in `commons`
- add the executable to the targets export (not sure if this can be useful to downstream projects)
- use a  list of targets so that we can generate `target_INCLUDE_DIRS` and `target_LIBRARY` in `NelsonConfig.cmake.in` for every installed target

### CODE REVIEW

**Review by Nelson-numerical-software — COMMENTED** [review]
Oh :) This seems to be great. I will take a look tonight. Many thanks

Do not forget to add you in https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/CONTRIBUTORS.md

About 'fmt', library is embedded because patched :(
https://github.com/Nelson-numerical-software/nelson/commit/c9f8dd3083c23d96bdf45780c920dcb84936c0fd

```matlab
A = NaN
B = Inf
```

**Comment by JohanMabille** [comment]
Thanks for the detail about `fmt`, I've added its headers as part of the `Commons` module package.

I've noticed that some packages have been stripped for most of their content (such as Integer or overload) and are not added to the list of modules to build; from my understanding they are still in the minimal project because some of their headers are required by other modules. However, now that we install the headers of the modules we build, we also need to install the headers they depend on. I think we have two options here:

- either we make these modules pure interface packages (like we package header-only libraries). This keep the code of this repo as is, but makes things more complicated when we port the changes to the nelson main repo
- we reincorporate the files that were removed and build the packages; this would increase the size of this repo bu simplify the port of the changes to Nelson.

**Comment by Nelson-numerical-software** [comment]
I will try to integrate/adapt all this modifications quickly in main repo (I will try to work on, it this weekend).
Unless you are interested in doing this in the main repo ? (I would be happy to this ;) )

" This keep the code of this repo as is, but makes things more complicated when we port the changes to the nelson main repo"
We can try this, until we talk about modules as packages to plug on minimal core if it is possible (?)

**Review by Nelson-numerical-software — APPROVED** [review]
LGTM
(Thanks)

**Comment by JohanMabille** [comment]
> I will try to integrate/adapt all this modifications quickly in main repo (I will try to work on, it this weekend). Unless you are interested in doing this in the main repo ? (I would be happy to this ;) )
> 
> " This keep the code of this repo as is, but makes things more complicated when we port the changes to the nelson main repo" We can try this, until we talk about modules as packages to plug on minimal core if it is possible (?)

I can start to work on it, I will probably have some questions regarding the structure (especially regarding the src / no-src / builtin subfolder and what they're meant for).

> " This keep the code of this repo as is, but makes things more complicated when we port the changes to the nelson main repo"
> We can try this, until we talk about modules as packages to plug on minimal core if it is possible (?)

It seems that these modules are only used "privately" by the other ones, so no need to install their headers in this repo, this keeps the code as is *and* does not complicate porting the change to the main repo for now.

**Comment by Nelson-numerical-software** [comment]
"It seems that these modules are only used "privately" by the other ones, so no need to install their headers in this repo, this keeps the code as is and does not complicate porting the change to the main repo for now."
Yes.  as for me, currently only engine, types and interpreter should be public (others should be private, no interest for users or advances users).

**Comment by JohanMabille** [comment]
Ok, I'll try to reduce the scope of the installed headers and make private as many modules as I can before porting the changes to the main repo.

**Comment by Nelson-numerical-software** [comment]
> Ok, I'll try to reduce the scope of the installed headers and make private as many modules as I can before porting the changes to the main repo.

I began to rework main repo. It will require also some modifications about load dynamically modules.
Previously all was under a main directory, after rework all will be splitted (It is more complicated in fact, it is why the commercial tool does not do as it even on linux)

**Comment by JohanMabille** [comment]
OK, thanks for the follow up

**Pull request merged**
