### PR TITLE
Added static build

### PR DESCRIPTION
**Pull request by JohanMabille**

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Can we leave it optional ?

**Comment by JohanMabille** [comment]
It is actually optional, you need to pass `-DBUILD_SHARED_LIBS=OFF` to make a static build. By default, the behavior is the same as before.

**Review by Nelson-numerical-software — APPROVED** [review]

**Comment by Hind-M** [comment]
I think removing `SHARED`  is missing from the following modules CMake files:
`linear_algebra`, `mex` and `overload`
There is also `module_library_builtin_name` where `SHARED` is specified and should be removed:
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/functions_manager/CMakeLists.txt#L44
The `builtin` there may be relevant but that may not be the case in [linear_algebra](https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/linear_algebra/CMakeLists.txt#L61), [mex](https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/mex/CMakeLists.txt#L84) and [integer](https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/integer/CMakeLists.txt#L56) modules since there is no builtin for now?

**Comment by JohanMabille** [comment]
> There is also module_library_builtin_name where SHARED is specified and should be removed:
https://github.com/Nelson-numerical-software/nelson-minimalist-core/blob/master/modules/functions_manager/CMakeLists.txt#L44

It is removed in this PR.

**Pull request merged**
